version: '2'
services:
  mysql:
    image: 'mysql:5.5'
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
